DELETE http://localhost:3003/api/blogs/5f351935ea72160d0880dafe
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBydWViYTEiLCJpZCI6IjVmMzUwNjZhNDBhYjRlNTM2OGIyM2IxOCIsImlhdCI6MTU5NzMxMTcxMH0.4QfoB5ZH5hUN87c7FaTCGaxt0D1vFDcml6ZP2glHgrQ