POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Prueba1",
    "name": "Prueba1",
    "password": "Prueba1"
}


###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "url": "https://xellex.es",
    "title": "Prueba",
    "author": "Alejandro Luna"
}
